/* eslint-disable prettier/prettier */
import { ApiProperty } from '@nestjs/swagger';
import { PaymentMethod, PaymentStatus } from '../../../utils/enum';
import { UserEntity } from 'src/moduls/user/entities/user.entity';
import { SubscriptionEntity } from 'src/moduls/subscription/entity/subscription.entity';

/**
 * PaymentResponseDto
 * -----------------------------------------------------
 * Represents a full response returned to the client after
 * retrieving payment information.
 *
 * This DTO is used for:
 * - Returning payment details after creation
 * - Returning payment details in "findOne" or "findAll"
 * - Returning payment details after Stripe confirmation
 *
 * It maps directly from PaymentEntity.
 */
export class PaymentResponseDto {
  @ApiProperty({
    example: 'p1a2b3c4-....',
    description:
      'Unique identifier of the payment record (UUID v4). ' +
      'Generated automatically by the system.',
  })
  payment_id: string;

  @ApiProperty({
    example: 9.99,
    description:
      'Total amount paid for this transaction. ' +
      'Stored in decimal format, represents the exact charged amount.',
  })
  amount: number;

  @ApiProperty({
    enum: PaymentMethod,
    example: PaymentMethod.CARD,
    description:
      'Defines the payment method used for the transaction. \n\n' +
      'Supported methods include:\n' +
      `- ${PaymentMethod.CARD}\n` +
      `- ${PaymentMethod.PAYPAL}\n` +
      `- ${PaymentMethod.WALLET}\n` +
      'You can extend this enum as needed.',
  })
  method: PaymentMethod;

  @ApiProperty({
    enum: PaymentStatus,
    example: PaymentStatus.SUCCESS,
    description:
      'Indicates the current status of the payment transaction. Possible values:\n' +
      `- ${PaymentStatus.PENDING}: Payment initiated but not completed yet\n` +
      `- ${PaymentStatus.SUCCESS}: Payment completed successfully\n` +
      `- ${PaymentStatus.FAILED}: Payment failed\n` +
      `- ${PaymentStatus.CANCELED}: Payment cancelled by the user or gateway\n`,
  })
  status: PaymentStatus;

  @ApiProperty({
    example: 'txn_123456',
    required: false,
    description:
      'The unique transaction ID generated by the payment provider (Stripe, PayPal...).\n' +
      'Use this ID for reconciliation, refunds, and provider-side debugging.',
  })
  transaction_id?: string;

  @ApiProperty({
    example: 'monthly',
    required: false,
    description:
      'Billing cycle associated with this payment. This value comes from the subscription plan.\n\n' +
      'Possible examples include:\n' +
      "- monthly\n" +
      "- yearly\n" +
      "- weekly\n\n" +
      'Useful when evaluating how often the user will be charged.',
  })
  billing_cycle?: string;

  @ApiProperty({
    example: '2025-02-10T12:30:00Z',
    description:
      'Timestamp of when the payment was created in the system.\n' +
      'Automatically generated by the database.',
  })
  payment_date: Date;

  @ApiProperty({
    description: 'User who made the payment',
    type: () => UserEntity,
  })
  user: UserEntity;

  @ApiProperty({
    description: 'Subscription associated with the payment',
    type: () => SubscriptionEntity,
    required: false,
  })
  subscription?: SubscriptionEntity;
}
